# Generated by Django 3.2 on 2022-03-25 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220325_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_sized',
            new_name='has_sizes',
        ),
    ]
